pipeline:
  name: android-client instrumented tests
  identifier: androidclient_instrumented_tests
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: fmegithubrunnersci
        repoName: android-client
        build: <+input>
  stages:
    - stage:
        name: Instrumented tests
        identifier: Instrumented_tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: large
              nestedVirtualization: true
          variables:
            - name: ANDROID_HOME
              type: String
              value: /opt/android-sdk
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: |
                      chmod +x .harness/scripts/install-deps.sh
                      .harness/scripts/install-deps.sh
              - step:
                  type: RunTests
                  name: Start Emulator and Run Tests
                  identifier: start_emulator_and_run_tests
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: connectedCheck --continue --stacktrace --info
                    shell: Sh
                    preCommand: |
                      # Set Android SDK environment variables to point to the same location
                      export ANDROID_SDK_ROOT=$ANDROID_HOME
                      
                      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
                      export PATH="$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin"

                      # Start emulator
                      chmod +x .harness/scripts/start-emulator.sh
                      .harness/scripts/start-emulator.sh
                    testIntelligence:
                      enabled: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/build/outputs/androidTest-results/connected/**/*.xml"
                          - "**/build/test-results/**/*.xml"
              - step:
                  type: Test
                  name: Publish Test Results
                  identifier: publish_test_results
                  spec:
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/build/outputs/androidTest-results/connected/**/*.xml"
                          - "**/build/test-results/**/*.xml"
                  when:
                    stageStatus: All
