pipeline:
  name: SDK_android-client_test
  identifier: SDK_androidclient_test
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  description: Tests for Android SDK
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdevops
        repoName: android-client
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build and test
                  identifier: build_and_test
                  spec:
                    shell: Sh
                    command: ./gradlew test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*/build/test-results/.*xml"
