pipeline:
  name: SDK_android-client_test
  identifier: SDK_androidclient_test
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  description: Tests for Android SDK
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdevops
        repoName: android-client
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: gradle test
                  identifier: gradle_test
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: test
                    runOnlySelectedTests: false
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: true
                    testSplitStrategy: TestCount
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Timeout
                          - Unknown
                        action:
                          type: Retry
                          spec:
                            onRetryFailure:
                              action:
                                type: MarkAsFailure
                            retryCount: 1
                            retryIntervals:
                              - 30s
                  strategy:
                    parallelism: 2
