pipeline:
  name: Android SDK unit tests
  identifier: Android_client_tests
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GH_androidclient
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: gradle test
                  identifier: gradle_test
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: true
                    testSplitStrategy: TestCount
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Retry
                spec:
                  retryCount: 1
