language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-15
    - android-15

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew test
