language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-17

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew test
