plugins {
    id 'com.android.library'
}

apply from: "$projectDir/../gradle/common-android-library.gradle"

android {
    namespace 'io.split.android.client.main'

    defaultConfig {
        multiDexEnabled true
        consumerProguardFiles "$projectDir/../split-proguard-rules.pro"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: 'true'

        testOptions {
            execution 'ANDROIDX_TEST_ORCHESTRATOR'
        }
    }

    buildFeatures {
        buildConfig true
    }

    sourceSets {
        test {
            java.srcDirs += 'src/sharedTest/java'
        }
        androidTest {
            java.srcDirs += 'src/sharedTest/java'
        }
    }

    buildTypes {
        debug {
            buildConfigField("String", "SPLIT_VERSION_NAME", "\"${rootProject.ext.splitVersion}\"")
            buildConfigField("String", "FLAGS_SPEC", "\"1.3\"")
        }
        release {
            buildConfigField("String", "SPLIT_VERSION_NAME", "\"${rootProject.ext.splitVersion}\"")
            buildConfigField("String", "FLAGS_SPEC", "\"1.3\"")
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
}

dependencies {
    // Public api modules
    api clientModuleProject('logger')
    api clientModuleProject('api')
    api clientModuleProject('http-api')
    api clientModuleProject('fallback')
    api clientModuleProject('backoff')
    api clientModuleProject('tracker')
    // Internal module dependencies
    implementation clientModuleProject('http')
    implementation clientModuleProject('events-domain')

    // External dependencies
    implementation libs.roomRuntime
    annotationProcessor libs.roomCompiler
    implementation libs.workRuntime
    implementation libs.lifecycleProcess
    implementation libs.annotation
    implementation libs.gson
    implementation libs.snakeyaml
    implementation libs.playServicesBase
    implementation libs.multidex

    // Test dependencies
    testImplementation libs.junit4
    testImplementation libs.mockitoCore
    testImplementation libs.mockitoInline
    testImplementation libs.kotlinStdlib
    testImplementation libs.kotlinTest
    testImplementation libs.kotlinTestJunit
    testImplementation libs.hamcrest
    testImplementation libs.commonsLang3
    testImplementation libs.guava
    testImplementation libs.okhttpMockwebserver
    testImplementation libs.okhttpTls

    // Android Test dependencies
    androidTestImplementation libs.androidxTestExtJunit
    androidTestImplementation libs.androidxTestRunner
    androidTestImplementation libs.androidxTestRules
    androidTestImplementation libs.workTesting
    androidTestImplementation libs.kotlinStdlib
    androidTestImplementation libs.kotlinTest
    androidTestImplementation libs.kotlinTestJunit
    androidTestImplementation libs.mockitoCore
    androidTestImplementation libs.mockitoAndroid
    androidTestImplementation libs.okhttpMockwebserver
    androidTestImplementation libs.okhttpTls
    androidTestImplementation libs.guava

    androidTestUtil libs.androidxTestOrchestrator
}

// Align Kotlin only for test and androidTest configurations to avoid duplicate classes
configurations.matching { it.name.toLowerCase().contains("test") }.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0"
    }
}
