plugins {
    id 'com.android.library'
}

apply from: "$projectDir/../gradle/common-android-library.gradle"

android {
    namespace 'io.split.android.client.fallback'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api clientModuleProject('logger')

    implementation libs.annotation

    testImplementation libs.junit4
    testImplementation libs.mockitoCore
}
