plugins {
    id 'com.android.library'
}

apply from: "$rootDir/gradle/common-android-library.gradle"

android {
    namespace 'io.split.android.streaming'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly libs.jetbrainsAnnotations
    implementation libs.annotation
    implementation libs.gson
    
    // Logger module for logging
    api project(':logger')

    testImplementation libs.junit4
    testImplementation libs.mockitoCore
}
