plugins {
    id 'com.android.library'
}

apply from: "$projectDir/../gradle/common-android-library.gradle"

android {
    namespace 'io.harness.events'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly libs.jetbrainsAnnotations

    testImplementation libs.junit4
    testImplementation libs.mockitoCore
}
