name: Internal deploy

on:
  push:
    branches:
      - 'development'
      - '*_baseline'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-app:
    name: Build App
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Publish
        run: ./gradlew publishDev
