name: instrumented tests

on: [ push ]

jobs:
  test:
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ram-size: 4096M
          script: ./gradlew connectedCheck
